### ISSUE TITLE
BluetoothDevice

### ISSUE THREAD

**Issue by bbevem** [d4rken/myolib#7]
In your description of Advance use, while trying to access the battery level, we must present the bluetooth device in constructor of BaseMyo. Can you please explain where can i get this BluetoothDevice?

``` java
BaseMyo baseMyo = new BaseMyo(getContext(), **bluetoothDevice**);
baseMyo.connect();
ReadMsg readMsg = new ReadMsg(Battery.BATTERYLEVEL, new MyoMsg.Callback() {
    @Override
    public void onResult(MyoMsg msg) {
        byte[] result = ((ReadMsg) msg).getValue();
    }
});
baseMyo.submit(readMsg);
```

**Comment by d4rken** [comment]
From Androids BluetoothManager
https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#startLeScan(android.bluetooth.BluetoothAdapter.LeScanCallback)
or have the MyoConnector directly constructor the object for you
https://github.com/d4rken/myolib/blob/b32b3d925de9737a566dcb45d22c2e08e507393c/myolib/src/main/java/eu/darken/myolib/MyoConnector.java#L77
