### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by faisalrugrugt** [d4rken/myolib#8]
I am using the library but it works on API 23 or less 
can you help me

**Comment by d4rken** [comment]
What's your question?

**Comment by faisalrugrugt** [comment]
when I run the app, its works on android 4.4 or less
I can't make it work for higher version

**Comment by d4rken** [comment]
What error does it give?
I've used it on higher APIs before.



Am 02.03.2018 16:49 schrieb "faisalrugrugt" <notifications@github.com>:

when I run the app, its works on android 4.4 or less
I can't make it work for higher version

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/d4rken/myolib/issues/8#issuecomment-369959253>, or mute
the thread

**Comment by faisalrugrugt** [comment]
Warning:The specified Android SDK Build Tools version (23.0.3) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by faisalrugrugt** [comment]
here's my build.gradle 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    defaultConfig {
        applicationId "net.lesan_tech.myo23"
        minSdkVersion 18
        targetSdkVersion 23
        versionCode 2
        versionName "1.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'eu.darken.myolib:myolib:0.0.2'
    repositories {
        maven {
            url 'C:\\Users\\AL deqa\\Desktop\\myo-android-sdk-0.10.0\\myorepository'
        }
    }
    compile 'com.thalmic:myosdk:0.10.+@aar'
}

**Comment by d4rken** [comment]
The dependencies were outdated (gradle/buildtools) for the latest Android Studio version.
I've updated the library and published `0.0.5` give that a try.
I've tested the example app on a Pixel@8.1.0 build with Android Studio 3.0.1.

**Comment by d4rken** [comment]
Also on newer versions you have to keep in mind that BLE needs location permission (but logcat should also show you a warning about that.

And your code snippet shows that you are using very old dependencies too in `net.lesan_tech.myo23`, I would update that too.

**Comment by faisalrugrugt** [comment]
Works like a charm ...thank you
